
Var integer_: integer;
  smallint_: smallint;
  longint_: longint;
  word_: word;
  byte_: byte;
  boolean_: boolean;
  char_: char;
  real_: real;
  single_: single;
  double_: double;
  extended_: extended;
  comp_: comp;
Procedure Example();
Begin
  write(' ', 'integer_');
  write(' ', ord(integer_));
  write(' ', pred(integer_));
  dec(integer_,2);
  write(' ', integer_);
  inc(integer_,2);
  write(' ', integer_);
  write(' ', succ(integer_));
  write(' ', high(integer_));
  write(' ', low(integer_));
  writeln;
  write(' ', 'smallint_');
  write(' ', ord(smallint_));
  write(' ', pred(smallint_));
  dec(smallint_,2);
  write(' ', smallint_);
  inc(smallint_,2);
  write(' ', smallint_);
  write(' ', succ(smallint_));
  write(' ', high(smallint_));
  write(' ', low(smallint_));
  writeln;
  write(' ', 'longint_');
  write(' ', ord(longint_));
  write(' ', pred(longint_));
  dec(longint_,2);
  write(' ', longint_);
  inc(longint_,2);
  write(' ', longint_);
  write(' ', succ(longint_));
  write(' ', high(longint_));
  write(' ', low(longint_));
  writeln;
  write(' ', 'word_');
  write(' ', ord(word_));
  write(' ', pred(word_));
  dec(word_,2);
  write(' ', word_);
  inc(word_,2);
  write(' ', word_);
  write(' ', succ(word_));
  write(' ', high(word_));
  write(' ', low(word_));
  writeln;
  write(' ', 'byte_');
  write(' ', ord(byte_));
  write(' ', pred(byte_));
  dec(byte_,2);
  write(' ', byte_);
  inc(byte_,2);
  write(' ', byte_);
  write(' ', succ(byte_));
  write(' ', high(byte_));
  write(' ', low(byte_));
  writeln;
  write(' ', 'boolean_');
  write(' ', ord(boolean_));
  write(' ', pred(boolean_));
  dec(boolean_,2);
  write(' ', boolean_);
  inc(boolean_,2);
  write(' ', boolean_);
  write(' ', succ(boolean_));
  write(' ', high(boolean_));
  write(' ', low(boolean_));
  writeln;
  write(' ', 'char_');
  write(' ', ord(char_));
  write(' ', pred(char_));
  dec(char_,2);
  write(' ', char_);
  inc(char_,2);
  write(' ', char_);
  write(' ', succ(char_));
  write(' ', high(char_));
  write(' ', low(char_));
  writeln;
End;
Begin
  example();
End.
